### ISSUE TITLE
reference to wrong path in the file __main__.py

### ISSUE THREAD

**Issue by timov50** [ericsalesdeandrade/number-logic#2]
I guess the line: 
`    input_list_example = number_example_obj.read_input_file("num_logic/src/input", "input1_short_version.txt")`

in the `__main__.py` should be:

`    input_list_example = number_example_obj.read_input_file("number_logic/src/input", "input1_short_version.txt")`

**Comment by ericsalesdeandrade** [comment]
Thanks for pointing this out @timov50. Pushed an update 👍
